### ISSUE TITLE
Preserve fields with empty array values when converting json to toml format?

### ISSUE THREAD

**Issue by kongyuhua** [squirrelchat/smol-toml#15]
Hello, when we use the stringify function to convert json to toml format, we find that some fields with a value of [] are sometimes lost (as shown below), and we hope to retain these fields. smol-toml is the latest version

![image](https://github.com/squirrelchat/smol-toml/assets/53422413/23e9db93-c170-491d-afbf-c57ae83065a5)

**Comment by cyyynthia** [comment]
That's a weird behavior, I'll investigate this and make sure they're not lost, as this shouldn't be happening.

**Comment by cyyynthia** [comment]
This has been fixed in v1.1.4
