### ISSUE TITLE
Entry point in package.json should be either `import` or `require`

### ISSUE THREAD

**Issue by silverwind** [squirrelchat/smol-toml#21]
https://bundlephobia.com/package/smol-toml shows a `EntryPointError` for this module which I think is because of this [usage of `default`](https://github.com/squirrelchat/smol-toml/blob/7eac80fceac2ce248fde4793522e5db481988e05/package.json#L40) in `package.json`, which according to [node docs](https://nodejs.org/dist/latest-v22.x/docs/api/packages.html#packages_conditional_exports) means:

> "default" - the generic fallback that always matches. Can be a CommonJS or ES module file.

A module file can only be either CommonJS or ESM, not both at the same time, and it appears the current file is CommonJS, so I suggest to use `require` instead of `default` to clearly specify the module is CommonJS because some tools might otherwise incorrectly interpret the `default` value as seen by bundlephobia.

PS: Another simpler variant for CommonJS modules is via main/types exports:

```json
"main": "./dist/index.js",
"types": "./dist/index.d.ts",
```

**Comment by cyyynthia** [comment]
1.2.1 is now published with exports recognized by bundlephobia. 🎉

It should be noted that despite being exported as CommonJS, treeshaking is in fact supported by most (if not all) major bundlers (considering the syntax used to specify exports).

**Comment by silverwind** [comment]
Thanks, definitely a good choice to not use `exports` for CommonJS as the ecosystem support is still not quite there, especially its object form. Even for ESM, I prefer to avoid the object form if there is only a single exported file.
