### ISSUE TITLE
Typescript error while using smol-toml

### ISSUE THREAD

**Issue by alMukaafih** [squirrelchat/smol-toml#24]
I get this error while compiling my code with TypeScript
```
node_modules/smol-toml/dist/error.d.ts:28:25 - error TS2552: Cannot find name 'ErrorOptions'. Did you mean 'TomlErrorOptions'?

28 type TomlErrorOptions = ErrorOptions & {
                           ~~~~~~~~~~~~


Found 1 error in node_modules/smol-toml/dist/error.d.ts:28
```

**Comment by alMukaafih** [comment]
Turns out you need to set your `tsconfig.json` target option to `es2022` or higher to use `smol-toml`

**Comment by cyyynthia** [comment]
This is expected; smol-toml does not support Node < 18 (it might work, but there is no support for this). Node 18 fully implements ES2022 and as such it is what your tsconfig should be targeting.

I generally recommend picking up configs from [tsconfig/bases](https://github.com/tsconfig/bases) which come with the necessary config for given environments. The preset for Node 18 does target ES2022.
