### ISSUE TITLE
Cannot import package

### ISSUE THREAD

**Issue by Hocdoc** [squirrelchat/smol-toml#3]
Hello,

Your TOML library looks very promising  to me.

Unfortunately I cannot import your library into any of my projects after I've installed it with `npm i smol-toml`:

`import { parse } from "smol-toml";`

=> error TS2307: Cannot find module 'smol-toml' or its corresponding type declarations. 

Maybe there is an issue with the packaging?

**Comment by cyyynthia** [comment]
Hi, that's indeed a problem!

What version of TypeScript are you using? Is the library actually impossible to import or is the problem only related to typing information?

**Comment by cyyynthia** [comment]
Actually, I've just tried and I seem to be able to reproduce this using stock TS config. By specifying `moduleResolution` to `node16` (or `nodenext`), TypeScript will actually resolve the types using my package.json's `exports` specification solving this issue.

This is not ideal, and considering I have a way to avoid this issue completely I'll change that in a future release. In the meantime, using the workaround described above should work.

**Comment by Hocdoc** [comment]
Sorry for my late response and thanks for your `moduleResolution`-tip!

**Comment by Wakeful-Cloud** [comment]
You need to add `"types": "./dist/index.d.ts"` and `"main": "./dist/index.js"` to the `package.json` ([Reference](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package)).

**Comment by cyyynthia** [comment]
TypeScript added support for NodeJS's `exports` field in TypeScript 4.7 and does correctly look up the `types` specified in this. `main` is unrelated to TypeScript and is useless in this context.

Realistically, failure to resolve the package's types is an indication of either an outdated TypeScript installation, or an improper configuration as I described above. While adding `types` at the root of the package is currently possible, it is only "accidental" and does not fully reflect the true Node Resolve Algorithm used.

References:
 - https://github.com/microsoft/TypeScript/blob/88cb76d314a93937ce8d9543114ccbad993be6d1/src/compiler/moduleSpecifiers.ts#L963-L982
 - https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing
 - https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#resolvepackagejsonexports
 - https://nodejs.org/api/packages.html#exports
 - https://nodejs.org/api/esm.html#resolution-algorithm-specification, PACKAGE_RESOLVE step 11-5
