### ISSUE TITLE
v1.3.1 changes?

### ISSUE THREAD

**Issue by silverwind** [squirrelchat/smol-toml#32]
v1.3.1 was published to npm but there are no relevant commits or a release for it, could you add them?

I'm always suspicious about npm publishes that do not link back to the data in git, I recommend publishing [with provenance](https://docs.npmjs.com/generating-provenance-statements), to create a verifyable link between npm and git data.

**Comment by cyyynthia** [comment]
I thought I had pushed the commits, my bad 😅

**Comment by silverwind** [comment]
All good, thanks for confirmation :)

**Comment by TheKodeToad** [comment]
A git tag and github release is missing too
