### ISSUE TITLE
The parser step is currently quite lossy, as it doesn't preserve comment information (nor formatting). If you read a toml file and stringify it back, it will produce a "full" table; which means mostly the same thing but is most likely unwanted.

### ISSUE THREAD

**Issue by NaNOteh** [squirrelchat/smol-toml#33]
The parser step is currently quite lossy, as it doesn't preserve comment information (nor formatting). If you read a toml file and stringify it back, it will produce a "full" table; which means mostly the same thing but is most likely unwanted.

Because the lib maps toml files to plain objects (without intermediary attributes), I'm not sure how to keep track of comments (and possibly other metadata such as "is this table an inline table" for formatting purposes) in the output. I'm not sure I like the extra key way, as this doesn't preserve information about where the comment was...

I thought about having the library expose metadata via `content[Symbol('smol-toml::metadata')]`, that'd be able to hold everything but I'm not sure about that approach either. It would allow any data to be in there so it could preserve everything (formatting, comments, etc...) making the lib suitable for non-destructive toml editing.

Do you have any opinions on this?

_Originally posted by @cyyynthia in https://github.com/squirrelchat/smol-toml/issues/17#issuecomment-2077133600_

**Comment by cyyynthia** [comment]
Why did you copy/paste that in a new issue? This only creates spam, this doesn't need to be a new issue.
